spring.application.name=grammy
client.labs.base-url=https://helios.cs.ifmo.ru:18868/grammy/band

server.ssl.enabled=true
server.port=18871
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=my-self-signed-cert

logging.level.root=OFF
logging.level.org.springframework=OFF
logging.level.org.springframework.boot=OFF
logging.level.org.springframework.web=OFF
logging.level.org.springframework.security=OFF

# ????????? Weld (CDI container)
logging.level.org.jboss.weld=OFF

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=OFF