spring.application.name=labs
server.port=8090

#spring.profiles.active=service1

# PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/soa_labs
spring.datasource.username=postgres
spring.datasource.password=ROOT

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.transaction.jta.platform=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=15s
management.endpoints.web.exposure.include=health

spring.cloud.consul.discovery.service-id=labs

#server.ssl.enabled=true
#server.port=18868

#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=123456
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=my-self-signed-cert